### ISSUE TITLE
about "progressively add new stages"

### ISSUE THREAD

**Issue by EchoWang99** [PRIS-CV/PMG-Progressive-Multi-Granularity-Training#7]
（model.py line:60)
def forward(self, x):
        xf1, xf2, xf3, xf4, xf5 = self.features(x)

        xl1 = self.conv_block1(xf3)
        xl2 = self.conv_block2(xf4)
        xl3 = self.conv_block3(xf5)
      。。。

In the code, model loads and trains all stages of the baseline model simultaneously, not as the paper says"train the low stage first and then progressively add new stages for training".
Did I get it wrong? Please help me understand better.

**Comment by RuoyiDu** [comment]
> （model.py line:60)
> 
> def forward(self, x):
> xf1, xf2, xf3, xf4, xf5 = self.features(x)
>     xl1 = self.conv_block1(xf3)
>     xl2 = self.conv_block2(xf4)
>     xl3 = self.conv_block3(xf5)
>   。。。
> 
> In the code, model loads and trains all stages of the baseline model simultaneously, not as the paper says"train the low stage first and then progressively add new stages for training".
> Did I get it wrong? Please help me understand better.

We do load model simultaneously. But if you take a look at "train.py" you will notice that each iteration contains several training steps and outputs from different stages are not trained simultaneously. Since the back propgation of low-level stages' outputs won't change the weights of high-level stages, these high-level stages can be regarded as progressively added.

**Comment by EchoWang99** [comment]
Thanks a lot！This really helps me.
